// Generated by CoffeeScript 1.4.0
(function() {
  var exec;

  exec = function(fn) {
    var script;
    script = document.createElement('script');
    script.setAttribute('type', 'text/javascript');
    script.textContent = '(' + fn + ')();';
    return document.body.appendChild(script);
  };

  exec(function() {
    $('body').bind('ajaxComplete', function() {
      var l, _i, _len, _ref, _results;
      _ref = document.querySelectorAll("a[href*='rooms']");
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        l = _ref[_i];
        _results.push(l.target = '_blank');
      }
      return _results;
    });
    return null;
  });

}).call(this);
